### ISSUE TITLE
Deprecate custom Homebrew tap in favour of official package

### ISSUE THREAD

**Issue by patrickhoette** [phrase/phrase-cli#107]
Phrase CLI has been added to the official Homebrew repository (See [this PR](https://github.com/Homebrew/homebrew-core/pull/103146)). Also make sure to change the instructions on the website and inform people who have the `phrase` package install that they should uninstall that and install `phrase-cli`.

**Comment by BradKwon** [comment]
Hi Phrase Team,

It is nice that the Phrase CLI installation via Homebrew got easier and I like that.
The only problem I see here is that although the tech support team said they are working on updating help center half a year ago, it's not been updated and the previous `brew install phrase` becomes unavailable as of yesterday.

And even make it worse, I couldn't find anywhere, which announced this halt, but this GitHub repository after spending one or two hours.

Maybe there is any communication channel that does it. If so, please let me know so I can subscribe or follow it to get up-to-date. Otherwise, it would be also good point to have it so customers can prepare for it.

It would be also helpful to update the official installation guide so it is easy to solve any changes.

**Comment by BradKwon** [comment]
Hi @theSoenke, thanks for this quick response.

I already updated my system to use a new way `brew install phrase-cli` so I don't need to do `brew tap`, which is nice 👍 

The way I see it, it should be fine once the official installation guide is updated.

**Comment by theSoenke** [comment]
Running `brew upgrade phrase` should now automatically upgrade to the formula in core and the docs will be updated in a moment as well
