### ISSUE TITLE
Better bad request reporting

### ISSUE THREAD

**Issue by rlisowski** [phrase/phrase-cli#12]
CLI should explain what went wrong, eg when you provide bad file format param for locales download. 

## Expected Behavior
Detailed error message

## Current Behavior
Error: 400 Bad Request

**Comment by fredv** [comment]
**Expected Behavior**: Get info on required format of --host (e.g. protocol://host:port/api/v2); or simply adding it to the host (complexity hiding for interface user)

**Expected Behavior**: Segfault if --host does not include /api/v2

**Comment by lukasreussner** [comment]
Better error handling in the CLI would be relay helpful. :)

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
