### ISSUE TITLE
respect project_id from the config file in all commands

### ISSUE THREAD

**Issue by rlisowski** [phrase/phrase-cli#16]
For now, only pull/push/cleanup are using a project_id from the config file, it should be used in any command.

**Comment by dsimon-onventis** [comment]
Would be great, especially for the "branches" command.
Right now I need to manually parse the phrase config to get the project ID...

**Comment by dsimon-onventis** [comment]
Any progress here, @rlisowski ?

**Comment by theSoenke** [comment]
@dsimon-onventis Unfortunately we don't have any update right now. I can't promise yet when we'll add this but I'll raise this internally again

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
