### ISSUE TITLE
.phrase.yaml or .phrase.yml?

### ISSUE THREAD

**Issue by json-derulo** [phrase/phrase-cli#17]
There is misleading information wheter the config file should be named `.phrase.yaml` or `.phrase.yml`.

If I run `phrase init`, it generates a `.phrase.yml` for me, but if I run `phrase help`, it says:

```
--config string         config file (default is ./.phrase.yaml fallback to $HOME/.phrase.yaml)
```

I tested it, and `.phrase.yml` is respected while `.phrase.yaml` isn't.

Personally I'd like to have `.phrase.yaml` working as well, because `yaml` is the [officially recommended extension](https://yaml.org/faq.html).

**Comment by rlisowski** [comment]
Right now we respect only `.phrase.yml` and `.phraseapp.yml` files.  I will fix the flag help description to reflect it.

With `--config` flag you can pass a file named whatever you want, even `some-specific-use-case.phrase-config-file.yaml` so you can use it with your `.phrase.yaml` config.

Adding new files is a little bit more problematic because those files need to be respected by Github and Gitlab sync too. I will raise it on the next planning.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
