### ISSUE TITLE
Escaping percentage (%) character

### ISSUE THREAD

**Issue by fplaten** [phrase/phrase-cli#28]
Hey guys,

we're using the CLI to great success but have one issue: We try to use the same texts for our iOS and our Android app. In some texts there happen to be percentage characters (%), which iOS needs to be escaped (%%). However Android just shows them as ' %%'. Is there an option comparable to the different injection placeholders to automatically add a % in iOS or to remove it for Android?

Thanks and best regards,
Florian

**Comment by theSoenke** [comment]
Hey @fplaten, could you reach out to our support team at https://phrase.com/contact/ or via the embedded chat on phrase.com to take a closer look at this? Thanks!

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.

**Comment by tajchert** [comment]
Can I ask you @egze  what was the solution?
As this is probably a very common question/problem it makes sense to publish this here and/or as part of your documentation (as sharing labels between Android and iOS is very common).

**Comment by jablan** [comment]
@tajchert phrase CLI is more or less just a wrapper around standard Phrase Strings features. In this particular case, if I understand correctly, it's about downloading translations from Phrase and different behaviour (bug?) in certain formats?
If that's the case, I'd indeed suggest contacting Phrase support.

**Comment by tajchert** [comment]
Ok, I will contact support for best practices on this topic. 👌
