### ISSUE TITLE
phrase pull by specific tag

### ISSUE THREAD

**Issue by ricardolyn** [phrase/phrase-cli#30]
Hey,

I know that `phraseapp pull` uses the yml, but sometimes I want that based on the YML configuration, pull only this specific tag (appended to the YML one) without pulling all strings or changing the YML for this, using the same files and not dividing by features.

If we divide by files, it will be a complicate configuration and number of files, as there are several teams with several features working at the same time, so isn't scalable.

**Comment by theSoenke** [comment]
This client has been deprecated and the issue moved to the new CLI v2 repo to keep track of the issue

**Comment by volo-droid** [comment]
It would be beneficial to have this feature implemented, esp. for a large project with a lot of locales and tags

**Comment by md-weber** [comment]
Is there any update on this issue? We want to use it to generate different translation file depending on the tag given in Phrase. 

To enable that, the cli or yaml file needed to have some options for that. 
Example: `phrase pull --tag Community`

<img width="167" alt="image" src="https://user-images.githubusercontent.com/8026644/122073458-b825ca80-cdf8-11eb-9d1b-efa752d1bf2a.png">

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.

**Comment by volo-droid** [comment]
@egze so, you've closed the public issues tracker, and moved issues handling to the private Customer Support area? 
That's quite disappointing 👎
