### ISSUE TITLE
Caching support for push/pull

### ISSUE THREAD

**Issue by dragosv** [phrase/phrase-cli#32]
Need to be able to only send the files that have changed, as if someone pushes 1000+ files daily, but most have not changed the push takes too long. Also this need to be a parameter on the CLI (--use-cache or similar). Should also support retrieving only the files that have changed as well.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
