### ISSUE TITLE
Aid installation automation on Windows

### ISSUE THREAD

**Issue by zlatinivanov-je** [phrase/phrase-cli#34]
We use internally [Chocolatey](https://chocolatey.org/) to automate dependencies installation on Windows. Would you consider adding a package there to help automate installation. It would be event better if you provide a package in a more cross platform package registry such ad `npm`, `yarn` or any other... It will make integration so much easier.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
