### ISSUE TITLE
generate token on login

### ISSUE THREAD

**Issue by AgDude** [phrase/phrase-cli#36]
Manually storing a token is an extra painful step for new users. Since you support password login, there should be an option to generate and automatically store a token.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
