### ISSUE TITLE
[request] Add a newline at the end of files in `phraseapp pull`

### ISSUE THREAD

**Issue by gfx** [phrase/phrase-cli#39]
I've configured my text editors to add a newline at the end of the file on save.

However,  files organized by`phraseapp pull` does not have the ending newline, it always makes diffs; thus I'd like for `phraseapp` to add newline at EOF.

Thanks.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
