### ISSUE TITLE
[request] Option to keep the order of keys, not sorting them

### ISSUE THREAD

**Issue by gfx** [phrase/phrase-cli#43]
Sorting keys in message files are bothering. It's awesome if there's an option to keep keys as is.

**Comment by iamandrewluca** [comment]
Can we at least know the algorithm that phrase uses to sort the keys? What is using internally for sorting?

**Comment by rlisowski** [comment]
You can check it in project settings

![image](https://user-images.githubusercontent.com/7737/98581435-c4c1cd80-22c1-11eb-9c5c-b50ee2f3bfb6.png)

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
