### ISSUE TITLE
Support multiple .phraseapp.yml files

### ISSUE THREAD

**Issue by gustavnikolaj** [phrase/phrase-cli#46]
Related to phrase/phraseapp-client#84 

As the other issue describes, having the `access_token` in the `.phraseapp.yml` file prevents us from checking it into our git repos. The workaround using the environment variable is not much better than having to pass it in as a flag.

Other cli tools that rely on config files often support layered configuration files. npm (the node package manager) is one such example.

If you run npm in a project `~/Projects/project` it will read your `.npmrc` file in `~/Projects/project` and extend any content into the one found in `~/.npmrc`.

That allows us to check in project specific configuration for npm into our projects and still allow users to put their auth tokens into the user specific `.npmrc`.

Having a similar feature would make the phraseapp-client much more usable.

--- 

As a workaround you can make a wrapper script that reads the access token from a file in the users home dir. The script can be added to a directory on PATH and be named to shadow the main phraseapp client binary.

```sh
#!/usr/bin/env bash

PHRASEAPP_BIN=...
ACCESS_TOKEN=`cat ~/.phraseapp_access_token`

PHRASEAPP_ACCESS_TOKEN=$ACCESS_TOKEN $PHRASEAPP_BIN "$@"
```

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact [support@phrase.com](mailto:support@phrase.com?subject=[GitHub]%20phrase-cli), and we can take more direct action toward finding a solution.
