### ISSUE TITLE
Brew reinstall old version

### ISSUE THREAD

**Issue by trollepierre** [phrase/phrase-cli#61]
My Issue is the CLI2 throws error because I don't use v2.0.26

But this scenario does not reinstall the last version, but an old v2.0.16 
I don't know what is wrong with the Phrase package.

+ When going the https://phrase.com/cli , I download some phrase_macosx_amd64 that I don't know how to run it.

Please clarify and stop random failing tests

![Capture d’écran 2021-01-12 à 10 58 01](https://user-images.githubusercontent.com/8363334/104301673-37207b00-54c8-11eb-8516-82386698c617.png)

**Comment by theSoenke** [comment]
@trollepierre Could you try running `brew upgrade phrase`? That should update the formula and afterwards you should have the latest client.

The update message is only a warning and should not block any operations with the client

**Comment by trollepierre** [comment]
The brew upgrade phrase got the same result!

<img width="481" alt="Capture d’écran 2021-01-13 à 18 34 16" src="https://user-images.githubusercontent.com/8363334/104487905-f6ab2500-55cd-11eb-8f5e-09334dc58809.png">

**Comment by theSoenke** [comment]
Could try running `brew update`, then `brew info phrase` and sent the output of the last command? `brew update` should update all formulas

**Comment by trollepierre** [comment]
Hello, after `brew update` mentioned 'Already up-to-date'
here is the output
<img width="641" alt="Capture d’écran 2021-01-15 à 12 30 11" src="https://user-images.githubusercontent.com/8363334/104720941-73a0e080-572d-11eb-9adf-7647c88eb21b.png">

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
