### ISSUE TITLE
modern way to install/update phrase CLI in Windows

### ISSUE THREAD

**Issue by igorlino** [phrase/phrase-cli#75]
We use Phrase in projects, and it CLI is quite nice.

I and others use [chocolatey](https://chocolatey.org/) to automate dependencies installation on Windows 10.  Its a very good counterpart to homebrew/MacOSx. 

I have seen there is already a package v1.17.1, which is definitively a bit old.
https://chocolatey.org/packages?q=phrase

Would you consider updating/adding a package there to help automate the installation, and most useful also, when there is an update, we get the latest version. ?

https://docs.chocolatey.org/en-us/create/create-packages

Thanks a lot,
Igor

**Comment by sbruhns** [comment]
Hi @igorlino, thanks for bringing this up. The package was not released by us. I will track this feature request internally and we keep you updated when there is a decision about adding support for chocolatey.

**Comment by igorlino** [comment]
@sbruhns  I just came across some interesting preview coming package manager from microsoft: winget, I read it last year but was just an announcement at that time.

https://github.com/microsoft/winget-cli
https://channel9.msdn.com/Shows/Tabs-vs-Spaces/Windows-Dev-Tools-WSL-Terminal-Package-Manager-and-more

probably chocolatey won't so happy about it, since they already have quite a good repository,  and winget just started last year.  
But, if looking at the good work they have been doing with Visual Studio Code, which has had massive global success, I think they are going to have it in a very good shape already during this year, and specially with the upcoming version of Windows 21h1

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
