### ISSUE TITLE
[Request] Auto accept Y on --use-local-branch-name

### ISSUE THREAD

**Issue by FDiskas** [phrase/phrase-cli#78]
Currently cli is used in CI and we would like to have auto accept questions like:
```
Should we create a new branch in Phrase with the same name and push to it? [y/N]:
```

The command is used like so and there is no way to skip interactive mode
```sh
./phrase_linux_amd64 push --use-local-branch-name -w   

You have currently checked out the branch 'feature/translations-using-branches'.
There currently is no branch in Phrase with this name.

Should we create a new branch in Phrase with the same name and push to it? [y/N]:
```

**Comment by theSoenke** [comment]
Thanks for the suggestion. That sounds like a quite useful feature. I can't promise yet when we'll add this but I'll keep you posted here when I have any news to share.

**Comment by FDiskas** [comment]
As a workaround in Bickucket piple step currently I'm using like so:
```
echo "Y" | ./phrase_linux_amd64 push --use-local-branch-name -w | grep --line-buffered -Po "Upload Id: \K\w+" | xargs -I{} echo ./phrase_linux_amd64 uploads cleanup -y --branch ${BITBUCKET_BRANCH} --id {}
```
> just a reference for others

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
