### ISSUE TITLE
Soft-Hyphen support (iOS & Android)

### ISSUE THREAD

**Issue by BlackHornet** [phrase/phrase-cli#82]
Hello,

we tried to add soft hyphen characters (https://www.compart.com/de/unicode/U+00AD) to our project, but noticed that iOS and Android need different "case-sensitive" texts.

on Android we have to use **\u00AD**
on iOS we have to use **\U00AD**

using unicodes in our phrase project is not possible due to this limitation.

Do you have a solution on how we can proceed, or do we have to use different phrase keys for each of the platform in that case?

Regards
Sebastian

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
