### ISSUE TITLE
Reference other keys in my translations

### ISSUE THREAD

**Issue by BlackHornet** [phrase/phrase-cli#83]
Is it possible to reference other keys in the project and automatically replace them in the generated files?

Example in Phrase:
key: example_key_source
value: TEST

key: example_key
value: This is a {{example_key_source}} key.

Generated files after `phrase pull`:
example_key_source => TEST
example_key => This is a TEST key.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
