### ISSUE TITLE
Pull .arb files with placeholders

### ISSUE THREAD

**Issue by foxted** [phrase/phrase-cli#84]
Hi there,

I noticed when using `phrase pull` that placeholders were missing in the locale files.

Is it supported by the CLI?

**Comment by theSoenke** [comment]
Hi @foxted, we're only pulling placeholders that were also part of the initial uploaded file. Otherwise, we can't know for sure how the placeholders are supposed to look like as the placeholder configuration can get quite complex for ARB files. 

We could also consider generating very basic placeholders during export if we have no ARB placeholders stored yet. Could you maybe also provide an example for a placeholder that you'd like to get during export. That would be really helpful. Thanks!

**Comment by foxted** [comment]
Hi @theSoenke, I think the most helpful would be adding the simple placeholders, like:

```arb
"pageHomeTitle" : "Welcome {firstName}",
  "@pageHomeTitle" : {
      "description" : "Welcome message on the Home screen",
      "placeholders": {
          "firstName": {}
      }
  },
```

 and eventually pluralization or gender/select ones with the ICU syntax (if active in the account):

```
"pageHomeBirthday": "{sex, select, male{His birthday} female{Her birthday} other{Their birthday}}",
  "@pageHomeBirthday": {
      "description": "Birthday message on the Home screen",
      "placeholders": {
          "sex": {}
      }
  },
```

PS: Using Flutter, the official phrase package does not generate ICU getters, it could be a nice addition as well. Currently using https://pub.dev/packages/intl_utils instead of the phrase package right now as we need ICU in our use case, but we had to give up the OTA goodness of Phrase 😥

**Comment by theSoenke** [comment]
Thanks for the additional information @foxted. We're now tracking this issue internally and will investigate to improve the placeholder behavior for ARB files.

That's of course unfortunate that the OTA SDK does not work yet for you due to the missing ICU getters. This is really valuable feedback and we have to take a closer look into the feasibility of this as well. I'll keep you updated here when there is any news

**Comment by theSoenke** [comment]
Hey @foxted, we've now released some improvements to the placeholder support. Placeholders in the format of `{name}` will now be added during export. ICU is a bit more complex and we haven't added support to automatically generate placeholders for them yet. But that is also something we would like to add as well
