### ISSUE TITLE
Rate limit exceeded

### ISSUE THREAD

**Issue by bitboxer** [phrase/phrase-cli#85]
I am currently trying to run `phrase pull` with version `2.2.0`  and see this error:

```
Rate limit exceeded. Download will resume in -9223372036 seconds
Error: 429 Too Many Requests for /path/to/file
```

The project is configured to store files in `./locales/<locale_name>/<tag>.json`, has 16 locales and 12 files in each language folder.

What do I need to do to pull all files from all locales? Currently, it can only pull 50% and then stops with the rate limit error.

**Comment by bitboxer** [comment]
I solved this for now by using the [outdated client](https://github.com/phrase/phraseapp-client), that one worked flawlessly.

**Comment by egze** [comment]
We have decided to close all GitHub issues and, instead, handle them through our Customer Support. We think this shift will allow us to offer proper prioritization of issues as well as a more appropriate response time that would be expected from Phrase products.

We apologize for any inconveniences this may cause. If you believe your issue is still relevant or has a high priority, please contact support@phrase.com, and we can take more direct action toward finding a solution.
